CREATE OR REPLACE TABLE `gcp-data-engineer-project-001.stagging.ventas`( 
orderNumber Numeric,
orderDate DATE,
customerNumber Numeric,
customerName STRING,
contactLastName STRING,
contactFirstName STRING,
cuscity STRING,
cusstate STRING,
cuscountry STRING,
salesRepEmployeeNumber NUMERIC,
amount NUMERIC ,
productCode STRING,
quantityOrdered Numeric,
priceEach Numeric,
OrderLineNumber Numeric, 
productName STRING,
productLine STRING,
productScale STRING,
productVendor STRING,
productDescription STRING,
textDescription STRING,
tlastName STRING,
firstName STRING,
officeCode STRING, 
reportsTo NUMERIC,
jobTitle STRING,
empcity STRING,
empstate STRING,
empcountry STRING,
empterritory STRING,
emppostalcode STRING)
PARTITION BY orderDate;